### ISSUE TITLE
Could not get qname from query

### ISSUE THREAD

**Issue by PoepieFloepie** [testdasi/pihole-dot-doh#12]
somtimes i see this in the log

Could not get qname from query: A helper function for dicts had a name argument that for a name that is not in the dict

is this from pihole cloudflare or stubby
is it bad ,or just ignore it

**Comment by testdasi** [comment]
I don't get this error but it comes from stubby. Someone did some digging on pihole discourse: https://discourse.pi-hole.net/t/stubby-crashes-when-pihole-cleanup-is-run-via-cron/52601/11
Looks harmless to me.
